import = ["/home/fayez/.config/alacritty/themes/themes/nord.toml"]

[window]
opacity = 0.90

[window.dimensions]
columns = 125
lines = 37

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

